twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    
services:
       twig.extension.text:
          class: Twig_Extensions_Extension_Text
          tags:
              - { name: twig.extension }