<?php

namespace App\Controller;

use Doctrine\ORM\EntityManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Doctrine\Common\Persistence\ObjectManager;


use App\Entity\Entry;
use App\Form\EntryType;

use App\Entity\Category;
use App\Form\CategoryType;


class FrontController extends AbstractController
{
    /**
     * @Route("/", name="front")
     */
    public function index()
    {
        return $this->render('front/index.html.twig', [
            'controller_name' => 'FrontController',
        ]);
    }
    
    /**
     *
     * @Route ("/login", name="login")
     */
    public function Login (){
        
        
        return $this->render ('admin/login.html.twig');
    }


    
    
    
    // Actor Management
    
    
    /**
     * @Route("/actors", name="actors")
     */
    public function Entrieslist()
    {
        $repo=$this->getDoctrine()->getRepository(Entry::class);
        $user = $this->getUser();
        if (null !== $user) {
        $actors=$repo->findAll();
        }
        else {
        $actors=$repo->findBy(['publish'=>'1']);
            
        }
        return $this->render('front/actors.html.twig', [
            'actors' => $actors
        ]);
    }
    
    
    
    /**
     * @Route("/actor/new", name="actor-new")
     * @Route("/actor/{id}", name="actor-update")
     
     */
    public function Entry(Entry $entry=null, Request $request, ObjectManager $om)
    {
        // create a new actor entity
        if (!$entry) {
            $entry= new Entry();
            
        }
        
        $user = $this->getUser();
        $form = $this->createForm(EntryType::class, $entry);
        if (null !== $user) {
            $form->add('publish');
        }
      
        //  create FormBuilder from form factory service

        
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
          
            $om->persist($entry);
            $om->flush();
            $this->addFlash(
                'alert-success',
                'nouvel acteur enregistré !'
                );
            return $this->redirectToRoute('actors');
            
        }else {
         
               return $this->render('front/actor-create.html.twig',  [
                    'formActor' => $form->createView()
            ]);
        }
        
    }
    /**
     * @Route("/actor/view/{id}", name="actor-view")
     */
    public function Entryview($id,Request $request, ObjectManager $om)
    {
        $repo= $this->getDoctrine()->getRepository(Entry::class);
        $entry=$repo->find($id);
        
        
        return $this->render('front/actor.html.twig',  [
            'actor' => $entry
        ]);
    }
    
    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    
    
    
    
}
